### ISSUE TITLE
I uesd it as a preference but has a NullPointException

### ISSUE THREAD

**Issue by z-twinkle-x** [1gravity/Android-ColorPicker#2]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TabHost.setup()' on a null object reference
                                                                        at com.onegravity.colorpicker.ColorPickerDialog.initTabs(ColorPickerDialog.java:177)
                                                                        at com.onegravity.colorpicker.ColorPickerDialog.show(ColorPickerDialog.java:87)
                                                                        at com.onegravity.colorpicker.ColorPickerPreference.onPreferenceClick(ColorPickerPreference.java:161)
                                                                        at android.preference.Preference.performClick(Preference.java:985)
                                                                        at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:214)
                                                                        at android.widget.AdapterView.performItemClick(AdapterView.java:305)
                                                                        at android.widget.AbsListView.performItemClick(AbsListView.java:1146)
                                                                        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3057)
                                                                        at android.widget.AbsListView$3.run(AbsListView.java:3864)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:211)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5373)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
                                                                        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

could you help me ?

**Comment by 1gravity** [comment]
I assume it doesn't inflate the layout correctly (dialog_color_picker.xml) or simply doesn't find it. I'd check the log for error messages previous to the stack trace. Anything related to layout inflation? How does your gradle build file look like?

**Comment by z-twinkle-x** [comment]
Sorry for my late reply, I have solved it, the reason is that I forget to
delete the old layout xml file that the last color-picker uses.
Thank you for your reply & sry for my poor English.  :D

2016年7月19日 03:42，"Emanuel Moecklin" notifications@github.com写道：
